spotify:
  client_id: "your_spotify_client_id"
  client_secret: "your_spotify_client_secret"
  redirect_uri: "your_redirect_uri"

discord:
  client_id: "your_discord_bot_client_id"

cache:
  directory: "lyrics_cache"
